experiment-1:

  # High data_quality is a config that might fail easily, or collapse.

  client-1:
    cores: 0.05 # equivalent to resources
    data_quality: 0.05 # equivalent to accuracy
    max_tp: 0.9 # equivalent to availability/latency

  client-2:
    cores: 0.2
    data_quality: 0.3
    max_tp: 0.5

  client-3:
    cores: 0.2
    data_quality: 0.6
    max_tp: 0.2

