experiment-1:

  # High data_quality is a config that might fail easily, or collapse.

  default:
    cores: 0.33 # equivalent to resources
    data_quality: 0.33 # equivalent to accuracy
    max_tp: 0.34 # equivalent to availability/latency

  high_perf:
    cores: 0.05
    data_quality: 0.05
    max_tp: 0.9

  low_cost:
    cores: 0.9
    data_quality: 0.05
    max_tp: 0.05

  high_quality:
    cores: 0.05
    data_quality: 0.65
    max_tp: 0.3

